module.exports = {
  product: '.sg-col-4-of-12.s-result-item.s-asin.sg-col-4-of-16.sg-col.sg-col-4-of-20',
  pName: '.a-size-base-plus.a-color-base.a-text-normal',
  sponsored: '.a-row.a-spacing-micro',
  merchant: '#merchant-info',
  bookMerch: '.print-sold-by td:nth-child(2)',
  otherMerch: '#availability',
  url: '.a-link-normal.a-text-normal',
  price: 'span.a-price-whole',
  rating: 'span.a-size-medium.a-color-base',
  noRating: '#cm-cr-dp-review-header',
  ratingDataHook: '[data-hook = \'total-review-count\']',
  reviewCountSel: 'span.a-size-base',
  brand: '#bylineInfo',
  bookAuth: '.author.notFaded',
  details: '#detailBullets_feature_div li .a-list-item',
  altDetailHead: '#productDetails_detailBullets_sections1 th',
  altDetailData: '#productDetails_detailBullets_sections1 td',
  altTechHead: '#productDetails_techSpec_section_1 th',
  altTechData: '#productDetails_techSpec_section_1 td',
}
